# Generated by Django 3.1.7 on 2021-04-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_register_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='contact',
            new_name='contact1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='empname',
            new_name='empname1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='password1',
        ),
    ]
