# Generated by Django 3.1.7 on 2021-04-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20210411_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='contact1',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='empname1',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='password',
        ),
        migrations.AddField(
            model_name='register',
            name='stdname',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
