# Generated by Django 3.1.7 on 2021-04-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20210411_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='stdid',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
