# Generated by Django 3.1.7 on 2021-04-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_register_stdid'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Paid',
            field=models.IntegerField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.CharField(default=' ', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='total_fee',
            field=models.IntegerField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=10),
        ),
    ]
