# Generated by Django 3.1.7 on 2021-04-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20210417_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Paid',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='total_fee',
            field=models.CharField(max_length=5),
        ),
    ]
