# Generated by Django 3.1.7 on 2021-04-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_auto_20210417_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Paid',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='contact',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='total_fee',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
