# Generated by Django 3.1.7 on 2021-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_auto_20210417_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='register',
            name='stdname',
            field=models.CharField(max_length=20),
        ),
    ]
