# Generated by Django 3.1.7 on 2021-04-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_auto_20210417_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Paid',
            new_name='paid_fee',
        ),
    ]
