# Generated by Django 3.1.7 on 2021-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_auto_20210417_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='stdid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='stdname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
